name: Baekjoon
description: 백준 문제를 관리하기 위한 템플릿입니다.
title: "\U0001F4AC [백준] : "
labels: "백준"

body:
  - type: markdown
    attributes:
      value: |
        [백준] :  123번 문제 와 같이 title을 작성해주세요
  - type: input
    id: problemLink
    attributes:
      label: 문제 URL
      description: 문제 URL를 작성해주세요
      placeholder: ex. https://www.acmicpc.net/problem/1003
    validations:
      required: true
  - type: dropdown
    id: level
    attributes:
      label: 문제의 난이도를 골라주세요
      multiple: false
      options:
        - Bronze
        - Silver
        - Gold
        - Platinum
        - Diamond
        - Ruby
    validations:
      required: true
  - type: dropdown
    id: levelDetail
    attributes:
      label: 문제의 난이도를 골라주세요
      multiple: false
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
    validations:
      required: true
  - type: textarea
    id: addComment
    attributes:
      label: talk
      description: 이슈에 관련된 아무말이나 해주세요
      placeholder: 이 말은 꼭 해야겠다.
    validations:
      required: false