name: Leetcode
description: Leetcode 문제를 관리하기 위한 템플릿입니다.
title: " [Leetcode] : "
# labels: ["Leetcode"]
assignees:
  - miewone
  - Mingjlee
  - dohyun0304
body:
  - type: markdown
    attributes:
      value: |
         [Leetcode] : 123번 문제 와 같이 title을 작성해주세요.
  - type: input
    id: contact
    attributes:
      label: 문제 URL
      description: 문제 URL를 작성해주세요
      placeholder: ex. https://leetcode.com/problems/time-needed-to-inform-all-employees/
    validations:
      required: true
  - type: dropdown
    id: ProblemLevels
    attributes:
      label: 문제의 난이도를 골라주세요
      multiple: false
      options:
        - Easy
        - Medium
        - Hard
  - type: textarea
    id: 추가할 말
    attributes:
      label: talk
      description: 이슈에 관련된 아무말이나 해주세요
      placeholder: "이 말은 꼭 해야겠다."
    validations:
      required: false